stages:
  - migrate

migrate_to_opensuse:
  image: opensuse
  stage: migrate
  script:
    - zypper update -y
    - zypper install -y  git curl python3 openssh sudo which binutils
    - git clone https://${USERNAME}:${PASSWORD}@gitlab.com/${USERNAME}/${LIBBASE}.git
    - mkdir -p ${CI_PROJECT_DIR}/content
    - cd ${CI_PROJECT_DIR}/content
    - bash ${CI_PROJECT_DIR}/${LIBBASE}/Tests/Pipeline/create.sh ${REPO}

migrate_to_ubuntu:
  image: ubuntu
  stage: migrate
  script:
    - apt update
    - apt upgrade -y
    - apt install -y git curl python3 ssh sudoA binutils
    - git clone https://${USERNAME}:${PASSWORD}@gitlab.com/${USERNAME}/${LIBBASE}.git
    - mkdir -p ${CI_PROJECT_DIR}/content
    - cd ${CI_PROJECT_DIR}/content
    - bash ${CI_PROJECT_DIR}/${LIBBASE}/Tests/Pipeline/create.sh ${REPO}

