group: travis_latest
sudo: required
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - clang
            - cmake3
      language: cpp
      compiler: clang

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - build-essential
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true

          packages:
            - gcc
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - gcc
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - gcc
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - gcc
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - gcc
            - cmake3
      language: cpp
      compiler: gcc

    - os: osx
      osx_image: xcode7.3 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode8.3
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.1 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.2 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.3 
      language: cpp
      compiler:
        - clang
        - gcc  
script:
  - git clone --branch Tests https://${USERNAME}:${PASSWORD}@review.gerrithub.io/a/hung0913208/LibBase ${LIBBASE} 
  - CI_PROJECT_DIR=$(pwd)
  - mkdir -p ${CI_PROJECT_DIR}/content
  - cd ${CI_PROJECT_DIR}/content
  - if [ $JOB = "build" ]; then bash ${TRAVIS_BUILD_DIR}/${LIBBASE}/Tests/Pipeline/Create.sh ${METHOD} ${REPO} ${BRANCH} ${PACKAGES}; fi
  - if [ $JOB = "reproduce" ]; then bash ${TRAVIS_BUILD_DIR}/${LIBBASE}/Tests/Pipeline/Reproduce.sh ${ISSUE} ${STEP} ${REPO} ${SPEC} ${AUTHOR}; fi

