group: travis_latest
sudo: required
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - clang
      language: cpp
      compiler: clang

    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - build-essential
      language: cpp
      compiler: gcc

    - os: linux
      language: android
      dist: trusty
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-x86-android-26
          - sys-img-armeabi-v7a-android-17c

    - os: osx
      osx_image: xcode7.3 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode8.3
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.1 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.2 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.3 
      language: cpp
      compiler:
        - clang
        - gcc  

before_install:
  - ./install-bazel-repo.sh
 
script:
  - git clone --branch Tests https://review.gerrithub.io/hung0913208/LibBase ${LIBBASE} 
  - CI_PROJECT_DIR=$(pwd)
  - mkdir -p ${CI_PROJECT_DIR}/content
  - cd ${CI_PROJECT_DIR}/content
  - bash ${TRAVIS_BUILD_DIR}/${LIBBASE}/Tests/Pipeline/Create.sh ${METHOD} ${REPO} ${BRANCH} ${PACKAGES}

