group: travis_latest
sudo: required
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          packages:
            - clang
            - cmake3
      language: cpp
      compiler: clang

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          packages:
            - build-essential
            - cmake3
      language: cpp
      compiler: gcc

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - cmake3
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
      language: cpp
      compiler: gcc-4.8

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - cmake3
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      language: cpp
      compiler: gcc-4.9

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - cmake3
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      language: cpp
      compiler: gcc-5

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - cmake3
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      language: cpp
      compiler: gcc-6

    - os: linux
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - cmake3
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      language: cpp
      compiler: gcc-7

    - os: osx
      osx_image: xcode7.3 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode8.3
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.1 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.2 
      language: cpp
      compiler:
        - clang
        - gcc

    - os: osx
      osx_image: xcode9.3 
      language: cpp
      compiler:
        - clang
        - gcc  
script:
  - git clone --branch Tests https://${USERNAME}:${PASSWORD}@review.gerrithub.io/a/hung0913208/LibBase ${LIBBASE} 
  - CI_PROJECT_DIR=$(pwd)
  - mkdir -p ${CI_PROJECT_DIR}/content
  - cd ${CI_PROJECT_DIR}/content
  - if [ $JOB = "build" ]; then bash ${TRAVIS_BUILD_DIR}/${LIBBASE}/Tests/Pipeline/Create.sh ${METHOD} ${REPO} ${BRANCH} ${PACKAGES}; fi
  - if [ $JOB = "reproduce" ]; then bash ${TRAVIS_BUILD_DIR}/${LIBBASE}/Tests/Pipeline/Reproduce.sh ${ISSUE} ${STEP} ${REPO} ${SPEC} ${AUTHOR}; fi

