version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Update newest apt's database
          command: apt update
      - run:
          name: Prepare the environment
          command: apt install -y git curl sudo
      - run:
          name: Clone Libbase repository
          command: git clone --branch Tests https://${USERNAME}:${PASSWORD}@dev.azure.com/blackcat0115/${LIBBASE}/_git/${LIBBASE}
      - run:
          name: Create a place for testing
          command: mkdir -p content
      - run:
          name: Trigger testing custom repositories
          command: cd content && bash $(pwd)/../${LIBBASE}/Tests/Pipeline/Create.sh ${METHOD} ${REPO} ${BRANCH} ${PACKAGES}
      - run:
          name: Remove everything for the next job
          command: rm -fr content && rm -fr ${LIBBASE}
  reproduce:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Update newest apt's database
          command: apt update
      - run:
          name: Prepare the environment
          command: apt install -y git curl sudo
      - run:
          name: Clone Libbase repository
          command: git clone --branch Tests https://${USERNAME}:${PASSWORD}@dev.azure.com/blackcat0115/${LIBBASE}/_git/${LIBBASE}
      - run:
          name: Create a place for testing
          command: mkdir -p content
      - run:
          name: Trigger testing custom repositories
          command: cd content && bash $(pwd)/../${LIBBASE}/Tests/Pipeline/Reproduce.sh ${ISSUE} ${STEP} ${REPO} ${SPEC} ${AUTHOR}
      - run:
          name: Remove everything for the next job
          command: rm -fr content && rm -fr ${LIBBASE}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - reproduce
