version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Update newest apt's database
          command: sudo apt update
      - run:
          name: Prepare the environment
          command: sudo apt install -y git curl sudo
      - run:
          name: Clone Libbase repository
          command: git clone --branch Tests https://review.gerrithub.io/${USERNAME}/LibBase.git ${LIBBASE}
      - run:
          name: Create a place for testing
          command: mkdir -p content
      - run:
          name: Trigger testing custom repositories
          command: cd content && bash $(pwd)/../${LIBBASE}/Tests/Pipeline/Create.sh
      - run:
          name: Remove everything for the next job
          command: rm -fr content && rm -fr ${LIBBASE}
  reproduce:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Update newest apt's database
          command: sudo apt update
      - run:
          name: Prepare the environment
          command: sudo apt install -y git curl sudo
      - run:
          name: Clone Libbase repository
          command: git clone --branch Tests https://review.gerrithub.io/${USERNAME}/LibBase.git ${LIBBASE}
      - run:
          name: Create a place for testing
          command: mkdir -p content
      - run:
          name: Trigger testing custom repositories
          command: cd content && bash $(pwd)/../${LIBBASE}/Tests/Pipeline/Create.sh
      - run:
          name: Remove everything for the next job
          command: rm -fr content && rm -fr ${LIBBASE}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - reproduce
