name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Show wellcome message
      run: echo Wellcome back again, miners
    - name: Run a multi-line script
      env:
        HOOK: ${{ secrets.HOOK }}
        LIBBASE: ${{ secrets.LIBBASE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        git clone --branch Tests https://review.gerrithub.io/${USERNAME}/LibBase ${LIBBASE} 
        CI_PROJECT_DIR=$(pwd)
        mkdir -p ${CI_PROJECT_DIR}/content
        cd ${CI_PROJECT_DIR}/content
        bash ${CI_PROJECT_DIR}/${LIBBASE}/Tests/Pipeline/Create.sh ${METHOD} ${REPO} ${BRANCH} ${PACKAGES}
